### ISSUE TITLE
Add FAS username to fedmsg message

### ISSUE THREAD

**Issue by hroncok** [fedora-infra/askbot-fedmsg#1]
When the user of Ask Fedora has his/her account paired with FAS account (i.e. (s)he logs in with it), the information should be visible in fedmsg stream, so the user activity may be watched (e.g. for badges). Currently, only the Ask Fedora username is used and there is no way to pair it with FAS except to guess that the username is the same.

Related tahrir bug: [Ask badges relate to username, but that's not working](https://github.com/fedora-infra/tahrir/issues/176)

**Comment by hroncok** [comment]
Can we use users e-mail address from askbot and check, if it's @fedoraproject.org or inFAS address?

**Comment by ralphbean** [comment]
> Can we use users e-mail address from askbot and check, if it's @fedoraproject.org or inFAS address?

Similarly, we could look for the openid login and see if it is `*.id.fedoraproject.org` to get the fas username (maybe).
